todo_list/tasks/urls.py
from django.urls import path

from tasks.views import task_list, task_update, task_create, task_delete


app_name = 'tasks'


urlpatterns = [
    path('', task_list, name='task_list'),
    path('create/', task_create, name='task_create'),
    path('tasks/<int:pk>/edit/', task_update, name='task_update'),
    path('tasks/<int:pk>/delete/', task_delete, name='task_delete'),
]

todo_list/todo_list/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('tasks.urls', namespace='tasks')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

todo_list/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import SignUp

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
]

todo_list/tasks/models.py
from django.db import models


TEXT_LIMIT = 20

STATUS_CHOICES = (
    ('done', 'Выполнено'),
    ('not_done', 'Не выполнено'),
)


class Task(models.Model):
    """Модель задачи."""
    description = models.TextField(
        verbose_name='Описание',
        max_length=1000,
    )
    status = models.CharField(
        verbose_name='Статус',
        max_length=8,
        choices=STATUS_CHOICES,
        default='not_done',
    )
    created = models.DateField(
        verbose_name='Дата создания',
        auto_now_add=True,
    )
    updated = models.DateField(
        verbose_name='Дата обновления',
        auto_now=True,
    )

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'
        ordering = ('status', )

    def __str__(self):
        return self.description[:TEXT_LIMIT]

todo_list/tasks/forms.py
from django import forms

from tasks.models import Task, STATUS_CHOICES


class TaskFilterForm(forms.Form):
    status = forms.ChoiceField(choices=STATUS_CHOICES)


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('description', 'status')

todo_list/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username',)

todo_list/tasks/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from tasks.forms import TaskForm, TaskFilterForm
from tasks.models import Task


@login_required
def task_list(request):
    """Все задачи."""
    form = TaskFilterForm(request.GET)
    tasks = Task.objects.all()

    if form.is_valid() and form.cleaned_data['status']:
        tasks = tasks.filter(status=form.cleaned_data['status'])

    return render(request, 'tasks/task_list.html', {'tasks': tasks, 'form': form})


@login_required
def task_create(request):
    """Создание новой задачи."""
    form = TaskForm(request.POST or None)

    if form.is_valid():
        form = form.save()
        form.save()
        return redirect('tasks:task_list')

    return render(request, 'tasks/task_create.html', {'form': form})


@login_required
def task_update(request, pk):
    """Изменение выбранной задачи."""
    task = get_object_or_404(Task, pk=pk)
    form = TaskForm(request.POST or None, instance=task)

    if form.is_valid():
        form.save()
        return redirect('tasks:task_list')
    
    context = {
        'form': form,
        'task': task,
    }
    return render(request, 'tasks/task_create.html', context=context)


@login_required
def task_delete(request, pk):
    """Удаление выбранной задачи."""
    task = get_object_or_404(Task, pk=pk)

    if request.method == 'POST':
        task.delete()
        return redirect('tasks:task_list')

    return render(request, 'tasks/task_delete.html', {'task': task})

todo_list/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from users.forms import CreationForm


class SignUp(CreateView):
    """Регистрация"""
    form_class = CreationForm
    success_url = reverse_lazy('tasks:task_list')
    template_name = 'users/signup.html'

todo_list/templates/base.html
<!DOCTYPE html>
{% comment %} {% load static %} {% endcomment %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% comment %} <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}"> {% endcomment %}
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    {% comment %} <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> {% endcomment %}
    <title> {% block title%} {% endblock %} </title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      <div class="container py-5">
        {% block content %}
        {% endblock %}
      </div>
    </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

todo_list/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>Todo</p>    
</footer>

todo_list/templates/includes/header.html
{% comment %} {% load static %} {% endcomment %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'tasks:task_list' %}">
        Todo
      </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" 
            href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" 
            href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>      
</header>

todo_list/templates/tasks/task_create.html
{% extends 'base.html' %}
{% block content %}
  <h1>{% if form.instance.pk %}Edit{% else %}New{% endif %} Task</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

todo_list/templates/tasks/task_delete.html
{% extends 'base.html' %}
{% block content %}
  <h1>Удаление задания</h1>
  <p>Вы уверены что хотите удалить "{{ task.description }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
    <a href="{% url 'tasks:task_list' %}">Не удалять</a>
  </form>
{% endblock %}

todo_list/templates/tasks/task_list.html
{% extends 'base.html' %}
{% block content %}
  <main> 
    <div class="container py-5"> 
      <h1>Task List</h1>
      <a href="{% url 'tasks:task_create' %}">Add new task</a>
      <form method="get">
        {{ form.as_p }}
        <button type="submit">Filter</button>
      </form>
      {% for task in tasks %}
        <li>
          {{ task.description }}
        </li>
        <li>
          {{ task.status }}
        </li>
        <li> 
          Дата публикации: {{ task.created|date:"d E Y" }} 
        </li>
        <li>
          <a href="{% url 'tasks:task_update' task.pk %}">Edit</a>
        </li>
        <li>
          <a href="{% url 'tasks:task_delete' task.pk %}">Delete</a>
        </li>
        {% if not forloop.last %}<hr>{% endif %} 
        {% empty %}
        <li>Пока что нет заданий.</li>
      {% endfor %}
    </div> 
  </main> 
{% endblock %}

todo_list/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <p>
    Вы вышли из своей учётной записи. Ждём вас снова!
  </p>
{% endblock %}

todo_list/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
  <h1>Login</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

todo_list/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Зарегистрироваться">
  </form>
{% endblock %} 